name: uc-14

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pull-requests: write
  contents: write

jobs:
  lint-and-security:
    name: Lint and Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install TFLint
        run: |
          wget https://github.com/terraform-linters/tflint/releases/download/v0.50.2/tflint_linux_amd64.zip
          unzip tflint_linux_amd64.zip
          sudo mv tflint /usr/local/bin/
          tflint --version

      - name: Run TFLint
        run: tflint --init && tflint -f compact
        working-directory: ./

      - name: Install Checkov
        run: |
          pip3 install --upgrade pip
          pip3 install checkov

      - name: Run Checkov
        run: checkov -d . --framework terraform --soft-fail
        working-directory: ./

  terraform:
    name: Terraform Operations
    runs-on: ubuntu-latest
    needs: lint-and-security

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GithubActionsTerraform

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ">= 1.12.1"

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./

      - name: fmt and Validate Terraform
        run: terraform fmt && terraform validate
        working-directory: ./

      - name: Generate Terraform Plan
        run: terraform plan -lock=false -out=tfplan.txt
        working-directory: ./

      - name: Generate Terraform Docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./
          output-file: README.md
          output-method: inject
          git-push: "true"

      - name: Apply Terraform
        run: terraform apply -lock=false -auto-approve tfplan.txt
        working-directory: ./

#      - name: Destroy Terraform
#       run: terraform destroy -lock=false -auto-approve
#        working-directory: ./
